language: generic
sudo: required
dist: trusty

addons:
  homebrew:
    packages:
      - autoconf
      - automake
      - gnutls
      - texinfo

os:
  - linux
  - osx

cache:
- directories:
  - "$HOME/emacs"

env:
  global:
    - PATH="$HOME/bin:$PATH"
    - EMAKE_SHA1=5bc70de1b562c1e5196e10a75df2a89f2e016de9
    - EMACS_DIR="$HOME/emacs"
    - EMACS="$HOME/emacs/src/emacs"
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=snapshot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

before_install:
  - make -f .travis.mk setup
  - make -f .travis.mk info

script:
  - make -f .travis.mk build/libegit2.so
  - make -f .travis.mk compile
  - make -f .travis.mk test
