language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

cache:
- directories:
  - "$HOME/emacs"

env:
  global:
    - PATH="$HOME/bin:$PATH"
    - MAKE="make -f .travis.mk"
    - EMAKE_SHA1=1b23379eb5a9f82d3e2d227d0f217864e40f23e0
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=snapshot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

before_install:
  - $MAKE -w emake.mk
  - $MAKE -w emacs

script:
  - $MAKE -w build/libegit2.so
  - $MAKE -w compile
  - $MAKE -w test
